### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by knkrth** [tyler124/Monitordroid-Web-Application#5]
hi thanks for making this open source but when i go to my server link i got a blank page so i try to figure out the problem so i decided to move the login.php from src directory to root then it works because its in root access on index.php and some of the function not worked so desiced to make a copy of all the files on the src directory to root then all function works fine except manage devices tab only not working.

**Comment by tyler124** [comment]
Hello,

We're currently in the process of reorganizing the structure of the source tree. We should have everything in the right place again soon.

Sorry for the mistakes and thank you for alerting us!

-Monitordroid Team

**Comment by adonisd** [comment]
the header searches for login.php in the root directory however it is in src/login.php. I copied everything in src/ directory to root and change virtual domain in apache to reflect the web directory and now everything seems to be working (Apart from change password). 

My solution is what I would call a dirty fix, if you have the patience for it I would wait for tyler124 to fix the structures. Thanks for making this open source!

**Comment by adonisd** [comment]
Hello tyler124, I can see you made a commit where you only updated the index.php. I tried this in the first place, it was still not enough to get this all working. Is it working now on your end?

**Comment by kartx22** [comment]
Hello Adonisd you were right there are lot of commit has to be done its all about rearranging the structure i have rearranged everything but still i have two bugs after the issue solved i will update it.

**Comment by mr-pagani** [comment]
Hi kartx22. I have tried your fix and I am not sure if I should wait for you to sort the bugs you speak of. Or maybe it's everyone for himself/herself :)
by the way, what are the two bugs you speak of?
cheers

**Comment by kartx22** [comment]
Hello mr-pagani its a communication error between client & the server side. I don't know weather server or client has the problem. When I launch the app I can able to register and I can see my registered mobile on the server but I can get only the client version number on the server nothing else like mobile model, etc are not response to the server. Now I'm not working on it. If you figure out the communication error let me know, have luck.

~kartx

**Comment by R-SecurityDown-Dev** [comment]
help, the problem still persists.

**Comment by R-SecurityDown-Dev** [comment]
@kartx you could compile ? add my whatsapp +5593991126488

**Comment by R-SecurityDown-Dev** [comment]
![blankpage](https://cloud.githubusercontent.com/assets/19401531/16360055/8e26111c-3b23-11e6-851a-e1175d0c524e.png)  issue :(

**Comment by kartx22** [comment]
@R-SecurityDown-Dev I drop this project long time ago. I'm not working on it anymore.

**Comment by R-SecurityDown-Dev** [comment]
@kartx22 gosh what a pity , I'm trying hard to make it work , however many problems are present.


you got some other app that does the same work as this ?

**Comment by R-SecurityDown-Dev** [comment]
really disheartening find tantaos bugs to be fixed , but I propose a
challenge , let's do this projet ovoltar working?

2016-06-26 5:42 GMT-04:00 kartx22 <notifications@github.com>:

**Comment by lordcharlx** [comment]
oops .... i think the developer retired

**Comment by lordcharlx** [comment]
wooop woop it works ... i just fix the bug

**Comment by kartx22** [comment]
@lordcharlx You fix the bug on server side or client side?

**Comment by lordcharlx** [comment]
the apk file.....

**Comment by lordcharlx** [comment]
fix the stuff on eclipse and android studio ......

**Comment by kartx22** [comment]
Can you make a pull request of your fixes on https://github.com/tyler124/Monitordroid

**Comment by lordcharlx** [comment]
https://www.sendspace.com/file/h0ddf7

**Comment by kartx22** [comment]
Thanks I check out & get to you back.

**Comment by lordcharlx** [comment]
hi pals does anyone has the gcm api and the key ???

**Comment by kartx22** [comment]
@lordcharlx You can create gcm cloud message api from google cloud messaging. If you have any trouble follow the link http://www.androidhive.info/2012/10/android-push-notifications-using-google-cloud-messaging-gcm-php-and-mysql/

**Comment by kartx22** [comment]
Without the gcm api how did you say I fixed the issue? you didn't tested it though.

**Comment by lordcharlx** [comment]
please contact me ......

**Comment by lordcharlx** [comment]
please whose got gcm api key and sender id share it here im going to make the monitordroid app open and free
![2016-10-25-175127_1366x768_scrot](https://cloud.githubusercontent.com/assets/5570136/19697859/90b336ee-9adc-11e6-89e4-002b2bc7556d.png)

**Comment by kartx22** [comment]
Get your own key on https://firebase.google.com/docs/cloud-messaging/

**Comment by lordcharlx** [comment]
@kartx whats update on your part ? any success

**Comment by kartx22** [comment]
Still I didn't check it.

**Comment by lordcharlx** [comment]
@ kartx drop your contact .... let's finish this up .....

**Comment by kartx22** [comment]
I don't want to continue this project so sry.

**Comment by lordcharlx** [comment]
Leave a comment lols .... given up so easily !

**Comment by kartx22** [comment]
Its a old project & I'm not interested in it. If you want you can continue this project.

**Comment by lordcharlx** [comment]
@kartx22  hmm so you ve got an app that does similar ?

**Comment by etispeza** [comment]
Looks like this problem couldn't be solved unfortunately!

**Comment by knkrth** [comment]
If anyone interested in similar application you can check out this repo https://github.com/kamushadenes/curiosus.git But it doesn't contain any readme steps to install and run server.
